# Generated by Django 2.0.4 on 2018-04-10 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('min_order_price', models.PositiveIntegerField(default=0)),
                ('avg_delivery_time', models.TimeField(default=datetime.time(0, 0))),
                ('restaurant_info', models.TextField(blank=True)),
                ('origin_info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '음식점',
                'verbose_name_plural': '음식점 목록',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.RestaurantCategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='order_types',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.RestaurantOrderType', verbose_name='주문유형'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.RestaurantTag', verbose_name='분류'),
        ),
    ]
