# Generated by Django 2.0.4 on 2018-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20180412_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantManager',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='img_cover_hover',
            field=models.ImageField(blank=True, upload_to='restaurant', verbose_name='커버 이미지(hover)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='restaurantcategory',
            name='name',
            field=models.CharField(choices=[('korean', '한식'), ('japanese', '일식'), ('cafe', '카페'), ('western', '양식'), ('etc', '퓨전'), ('flour', '분식'), ('hamburger', '햄버거'), ('chicken', '치킨'), ('chinese', '중식'), ('pizza', '피자')], max_length=20),
        ),
    ]
