# Generated by Django 2.0.4 on 2018-04-20 09:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurant_avg_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='구글 Place ID'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='좌표'),
        ),
    ]
