FROM            python:3.6.5-slim
MAINTAINER      dev@lhy.kr

ENV             LANG    C.UTF-8
ENV             LC_ALL  C.UTF-8

RUN             apt -y update && apt -y dist-upgrade
RUN             apt -y install build-essential nginx supervisor

COPY            ./requirements.txt  /srv/
RUN             pip install -r /srv/requirements.txt
