# Generated by Django 2.0.4 on 2018-04-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderreview_orderreviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_menus', to='restaurants.Menu', verbose_name='메뉴'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.Order'),
        ),
    ]
